"""Merges every worker's output/<worker_id>/part-*.jsonl into one HF-ready
dataset under hf_dataset/, matching the toorgil/mongolian-llm-benchmark
column layout plus this project's modality/media_path/pair_id additions.

Safe to run repeatedly while workers are still going (e.g. nightly) --
it always reads the full current output/ tree and rewrites hf_dataset/
from scratch; nothing here mutates output/, so re-running costs time, not
correctness.

Usage: python -m pipeline.dedup_merge
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from . import config as cfgmod

log = logging.getLogger("dedup_merge")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

COLUMNS = ["id", "source", "category", "type", "instruction", "input", "choices",
           "answer", "thinking", "difficulty", "language", "modality", "media_path", "pair_id"]


def load_all_rows(output_dir: Path) -> pd.DataFrame:
    rows = []
    seen_ids = set()
    dup = 0
    part_files = sorted(output_dir.glob("*/part-*.jsonl"))
    log.info("reading %d shard files under %s", len(part_files), output_dir)
    for pf in part_files:
        with open(pf, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if row["id"] in seen_ids:
                    dup += 1
                    continue
                seen_ids.add(row["id"])
                rows.append(row)
    log.info("loaded %d unique rows (%d duplicates skipped)", len(rows), dup)
    if not rows:
        return pd.DataFrame(columns=COLUMNS)
    df = pd.DataFrame(rows)
    for col in COLUMNS:
        if col not in df.columns:
            df[col] = None
    return df[COLUMNS]


def deterministic_split(df: pd.DataFrame, validation_rows: int, test_rows: int):
    """Hash-based split so re-running merge never reshuffles a row that's
    already been assigned to train/val/test in a previous run (as long as
    `id` -- a content hash -- doesn't change)."""
    import hashlib

    def bucket(rid: str) -> int:
        return int(hashlib.sha256(rid.encode()).hexdigest(), 16) % 1_000_000

    df = df.copy()
    df["_bucket"] = df["id"].map(bucket)
    df = df.sort_values("_bucket")
    n = len(df)
    test_n = min(test_rows, max(0, n // 10))
    val_n = min(validation_rows, max(0, (n - test_n) // 10))
    test_df = df.iloc[:test_n].drop(columns="_bucket")
    val_df = df.iloc[test_n:test_n + val_n].drop(columns="_bucket")
    train_df = df.iloc[test_n + val_n:].drop(columns="_bucket")
    return train_df, val_df, test_df


def main():
    cfg = cfgmod.load()
    output_dir = Path(cfg["paths"]["output_dir"])
    hf_dir = Path(cfg["paths"]["hf_dataset_dir"])
    data_dir = hf_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    df = load_all_rows(output_dir)
    train_df, val_df, test_df = deterministic_split(
        df, cfg["split"]["validation_rows"], cfg["split"]["test_rows"])

    for name, split_df in [("train", train_df), ("validation", val_df), ("test", test_df)]:
        path = data_dir / f"{name}-00000-of-00001.parquet"
        split_df.to_parquet(path, index=False)
        log.info("wrote %s: %d rows -> %s", name, len(split_df), path)

    readme = hf_dir / "README.md"
    if not readme.exists():
        readme.write_text(_dataset_card(cfg, len(train_df), len(val_df), len(test_df)),
                           encoding="utf-8")
    log.info("done. load with: datasets.load_dataset('parquet', data_dir='%s')", data_dir)


def _dataset_card(cfg: dict, n_train: int, n_val: int, n_test: int) -> str:
    return f"""---
language: [mn, en]
license: cc-by-4.0
tags: [mongolian, benchmark, llm-training, multimodal, bilingual]
---

# Mongolian-English multimodal SFT data

Generated by data_prepare/ using {cfg['ollama']['instructed_model']}
(base: {cfg['ollama']['base_model']}) with high-effort thinking traces
enabled, over a distributed Docker Swarm cluster.

Same column layout as `toorgil/mongolian-llm-benchmark`, extended with
`modality` (text/image/audio), `media_path`, and `pair_id` (links the
Mongolian and English row generated from the same source item, so every
piece of knowledge is represented in both languages).

Splits: train={n_train}, validation={n_val}, test={n_test}.
"""


if __name__ == "__main__":
    main()
